"""
ansys.py - ANSYS MAPDL validation job request, solver manifest, and result verification contracts.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from pydantic import Field, field_validator, model_validator
from cocoon_contracts.common import AwareDatetime, ContractModel, SCHEMA_VERSION


class AnsysJobStatus(str, Enum):
    """
    Finite state machine for ANSYS validation jobs strictly matching PRD Section 14.9.
    """
    NOT_REQUESTED = "NOT_REQUESTED"
    QUEUED = "QUEUED"
    PREPARING = "PREPARING"
    MESHING = "MESHING"
    SOLVING = "SOLVING"
    EXPORTING = "EXPORTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    UNAVAILABLE = "UNAVAILABLE"


class AnsysSolverConfig(ContractModel):
    """Execution parameters for the local or worker PyMAPDL simulation."""
    element_size_m: float = Field(default=0.25, gt=0.0, description="Global element mesh size (m)")
    element_type: str = Field(default="SOLID70", description="ANSYS thermal element formulation (e.g. SOLID70, SOLID90)")
    substeps_min: int = Field(default=1, ge=1, description="Minimum substeps per transient hour")
    substeps_max: int = Field(default=20, ge=1, description="Maximum substeps per transient hour")
    timeout_seconds: int = Field(default=3600, gt=0, description="Execution timeout limit in seconds")


class AnsysArtifactManifest(ContractModel):
    """Catalog and cryptographic hashes of files generated by an ANSYS run."""
    artifacts: dict[str, str] = Field(description="Map of artifact logical name to relative file path or URI")
    checksums_sha256: dict[str, str] = Field(description="SHA-256 hashes of generated artifacts")


class AnsysComparisonMetrics(ContractModel):
    """Statistical agreement metrics comparing independent RC and ANSYS thermal results."""
    mae_c: float | None = Field(default=None, description="Mean Absolute Error in °C")
    rmse_c: float | None = Field(default=None, description="Root Mean Squared Error in °C")
    max_abs_error_c: float | None = Field(default=None, description="Maximum Absolute Error in °C")
    r_squared: float | None = Field(default=None, description="Coefficient of determination [0..1]")
    bias_c: float | None = Field(default=None, description="Mean signed bias (ANSYS - RC) in °C")


class AnsysJobRequest(ContractModel):
    """Submitted job package for independent finite element thermal validation."""
    schema_version: Literal["4.0"] = Field(description="Contract schema version, strictly '4.0'")
    job_id: str = Field(description="Unique ANSYS job identifier starting with 'ans_'")
    design_revision_id: str = Field(description="Immutable design revision ID (rev_...)")
    weather_snapshot_id: str = Field(description="Immutable weather snapshot ID (wx_...)")
    solver_config: AnsysSolverConfig = Field(description="Solver meshing and stepping configuration")
    input_hashes: dict[str, str] = Field(description="Hashes of frozen input files forming this package")
    priority: int = Field(default=0, description="Scheduling priority tier (0=normal, 1=high)")
    submitted_at: AwareDatetime = Field(description="Job submission timestamp")
    imposed_indoor_temp_forbidden: bool = Field(
        default=True,
        description="Integrity guard asserting that RC indoor temperatures are never prescribed as boundary loads"
    )

    @field_validator("job_id")
    @classmethod
    def validate_job_id(cls, v: str) -> str:
        if not v.startswith("ans_"):
            raise ValueError(f"job_id '{v}' must start with 'ans_'")
        return v

    @field_validator("design_revision_id")
    @classmethod
    def validate_revision_id(cls, v: str) -> str:
        if not v.startswith("rev_"):
            raise ValueError(f"design_revision_id '{v}' must start with 'rev_'")
        return v

    @field_validator("weather_snapshot_id")
    @classmethod
    def validate_weather_id(cls, v: str) -> str:
        if not v.startswith("wx_"):
            raise ValueError(f"weather_snapshot_id '{v}' must start with 'wx_'")
        return v

    @model_validator(mode="after")
    def validate_request(self) -> AnsysJobRequest:
        if not self.imposed_indoor_temp_forbidden:
            raise ValueError(
                "SCIENTIFIC INTEGRITY VIOLATION: RC-predicted indoor temperature must NEVER be passed as an imposed ANSYS boundary condition."
            )
        return self


class AnsysValidationResult(ContractModel):
    """Outcome and comparison package produced by the ANSYS validation worker."""
    schema_version: Literal["4.0"] = Field(description="Contract schema version, strictly '4.0'")
    job_id: str = Field(description="ANSYS job identifier starting with 'ans_'")
    design_revision_id: str = Field(description="Target design revision ID (rev_...)")
    status: AnsysJobStatus = Field(description="Terminal or active execution status")
    started_at: AwareDatetime | None = Field(default=None, description="Worker pickup timestamp")
    completed_at: AwareDatetime | None = Field(default=None, description="Completion timestamp")
    error_reason: str | None = Field(default=None, description="Explanation if job failed, cancelled, or unavailable")
    solver_summary: dict[str, Any] | None = Field(default=None, description="Mesh nodes/elements and solver log stats")
    metrics: AnsysComparisonMetrics | None = Field(default=None, description="Comparison metrics against RC")
    artifacts: AnsysArtifactManifest | None = Field(default=None, description="Rendered PNGs, series CSVs, and logs")

    @field_validator("job_id")
    @classmethod
    def validate_job_id(cls, v: str) -> str:
        if not v.startswith("ans_"):
            raise ValueError(f"job_id '{v}' must start with 'ans_'")
        return v

    @field_validator("design_revision_id")
    @classmethod
    def validate_revision_id(cls, v: str) -> str:
        if not v.startswith("rev_"):
            raise ValueError(f"design_revision_id '{v}' must start with 'rev_'")
        return v

    @model_validator(mode="after")
    def validate_ansys_result(self) -> AnsysValidationResult:
        # Status consistency checks
        if self.status == AnsysJobStatus.COMPLETED:
            if self.artifacts is None:
                raise ValueError("Completed ANSYS validation job must include an AnsysArtifactManifest")
            if self.completed_at is None:
                raise ValueError("Completed ANSYS validation job must include completed_at timestamp")

        if self.status in (AnsysJobStatus.FAILED, AnsysJobStatus.UNAVAILABLE, AnsysJobStatus.TIMED_OUT):
            if not self.error_reason:
                raise ValueError(
                    f"ANSYS validation job with status '{self.status}' must provide an error_reason"
                )
        return self
