"""
evidence.py - Run the PRD v4 §14.11 evidence set and the §14.7 mesh check,
then generate evidence/EVIDENCE_INDEX.json and evidence/M8_VALIDATION_REPORT.md
from the job outputs (no hand-typed numbers).

    python -m cocoon_ansys.evidence            # run what is missing, then report
    python -m cocoon_ansys.evidence --report   # report only
    python -m cocoon_ansys.evidence --force    # re-run everything

Resumable: a case/level with a COMPLETED job is not re-run.
"""

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from cocoon_ansys.contracts_io import now_utc, write_json
from cocoon_ansys.paths import CASES_DIR, EVIDENCE_DIR
from cocoon_ansys.worker import read_status, recompare, run_job, submit

WEATHER = CASES_DIR / "wx_leh_20260124T11_48h.json"
MATERIALS = CASES_DIR / "materials_m0_standard.json"
STANDARD_SIZE = 0.25
CASES = {
    "case_01_baseline_single": "Baseline single-zone (uninsulated stone)",
    "case_02_insulated_single": "Improved insulated single-zone (mass inside PUF)",
    "case_03_airlock_living": "Airlock + living room (M0 fixture)",
    "case_04_two_floor": "Two-floor: airlock + living, sleeping above living",
}
MESH_LEVELS = {"case_03_airlock_living": (0.40, 0.25, 0.15),
               "case_04_two_floor": (0.40, 0.25, 0.18)}
TIMESTEP_CHECK = ("case_03_airlock_living", 8)          # 450 s vs standard 900 s


def _completed(root):
    for st in sorted(Path(root).glob("ans_*/status.json"), reverse=True):
        if read_status(st.parent).status == "COMPLETED":
            return st.parent
    return None


def _run(root, case, size, substeps=4, images=True, force=False):
    root = Path(root)
    if not force:
        done = _completed(root)
        if done:
            print(f"[evidence] {root.relative_to(EVIDENCE_DIR)}: reuse {done.name}")
            return done
    root.mkdir(parents=True, exist_ok=True)
    _, jd = submit(CASES_DIR / f"{case}.json", WEATHER, MATERIALS, element_size=size,
                   substeps=substeps, timeout=5400, jobs_root=root)
    print(f"[evidence] {root.relative_to(EVIDENCE_DIR)}: running {jd.name}", flush=True)
    st = run_job(jd, export_images=images)
    print(f"[evidence]   -> {st.status} {st.error_reason or ''}", flush=True)
    return jd


def run_all(force=False):
    for case in CASES:
        _run(EVIDENCE_DIR / case, case, STANDARD_SIZE, force=force)
    for case, levels in MESH_LEVELS.items():
        for size in levels:
            if size == STANDARD_SIZE:
                continue
            _run(EVIDENCE_DIR / "mesh_check" / case / f"h{size:.2f}", case, size,
                 images=False, force=force)
    case, sub = TIMESTEP_CHECK
    _run(EVIDENCE_DIR / "timestep_check" / case / f"substeps{sub}", case, STANDARD_SIZE,
         substeps=sub, images=False, force=force)


def _zone_series(job):
    return pd.read_csv(job / "temperature_series.csv")


def _diff(a_job, b_job):
    a, b = _zone_series(a_job), _zone_series(b_job)
    out = {}
    for c in a.columns:
        if c.startswith("T_") and c.endswith("_C") and "_min_" not in c and "_max_" not in c:
            d = (a[c] - b[c]).abs()
            out[c[2:-2]] = {"max_abs_diff_c": round(float(d.max()), 4),
                            "mean_abs_diff_c": round(float(d.mean()), 4)}
    return out


def report():
    idx = {"generated_at": now_utc().isoformat(), "weather": WEATHER.name,
           "standard_element_size_m": STANDARD_SIZE, "cases": {}, "mesh_check": {},
           "timestep_check": {}}
    lines = ["# M8 ANSYS validation evidence", "",
             "Generated by `python -m cocoon_ansys.evidence --report` from the job folders "
             "below. Every number comes from `comparison_metrics.json`, "
             "`solver_manifest.json` or `temperature_series.csv` of an immutable job.", "",
             "**Scope.** RC (thermal-calculator/multiroom_rc.py) and ANSYS MAPDL solve the SAME "
             "frozen scenario independently: 48 h, coldest window of winter 2025-26 at Leh "
             "(`" + WEATHER.name + "`), free-floating (no heater), airflow excluded on both "
             "sides, uniform 10 °C start. ANSYS never receives an RC temperature. Metrics "
             "describe agreement for these exact revisions only; they are not a general "
             "accuracy claim.", "",
             "## Evidence cases (PRD §14.11)", "",
             "| Case | Revision | Zones | Nodes / elements | Runtime | Pooled MAE | RMSE | Max abs | Bias (ANSYS−RC) | Diagnostic MAE¹ | Status |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    zone_lines = ["", "## Per-zone agreement", "",
                  "| Case | Zone | ANSYS mean °C | RC mean °C | ANSYS min °C | RC min °C | MAE °C | Max abs °C | Bias °C | Room-side envelope loss ANSYS / RC (W, mean) | Diagnostic¹ MAE / bias °C |",
                  "|---|---|---|---|---|---|---|---|---|---|---|"]
    for case, title in CASES.items():
        job = _completed(EVIDENCE_DIR / case)
        if not job:
            lines.append(f"| {title} | — | — | — | — | — | — | — | — | — | not run |")
            continue
        st = read_status(job)
        cm = json.loads((job / "comparison_metrics.json").read_text(encoding="utf-8"))
        sm = json.loads((job / "solver_manifest.json").read_text(encoding="utf-8"))
        p = cm["pooled"]
        dg = cm["diagnostics"]["position_weighted_capacitance"]
        rel = job.relative_to(EVIDENCE_DIR).as_posix()
        idx["cases"][case] = {"title": title, "job": rel, "revision": st.design_revision_id,
                              "metrics": p, "zones": cm["zones"],
                              "nodes": sm["nodes"], "elements": sm["elements"],
                              "runtime_s": sm["runtime_s"]}
        lines.append(f"| {title} | `{st.design_revision_id}` | {len(cm['zones'])} | "
                     f"{sm['nodes']} / {sm['elements']} | {sm['runtime_s']:.0f} s | "
                     f"{p['mae_c']:.2f} °C | {p['rmse_c']:.2f} | {p['max_abs_error_c']:.2f} | "
                     f"{p['bias_c']:+.2f} | {dg['pooled']['mae_c']:.2f} °C | "
                     f"[COMPLETED]({rel}/validation_summary.json) |")
        for zid, z in cm["zones"].items():
            env = (f"{z['envelope_loss_ansys_mean_w']:.0f} / {z['envelope_loss_rc_mean_w']:.0f}"
                   if "envelope_loss_ansys_mean_w" in z else "—")
            zone_lines.append(f"| {case} | {zid} | {z['ansys_mean_c']:.2f} | {z['rc_mean_c']:.2f} | "
                              f"{z['ansys_min_c']:.2f} | {z['rc_min_c']:.2f} | {z['mae_c']:.2f} | "
                              f"{z['max_abs_error_c']:.2f} | {z['bias_c']:+.2f} | {env} | "
                              f"{dg['zones'][zid]['mae_c']:.2f} / {dg['zones'][zid]['bias_c']:+.2f} |")
    lines += zone_lines
    lines += ["", "¹ **Diagnostic, not the official RC result.** Same ANSYS output compared with "
              "multiroom_rc re-run with position-weighted wall capacitance (each layer counts "
              "exp(−R_to_room/0.8) of its mass, the rule of the legacy single-zone model) "
              "instead of the flat `EFFECTIVE_MASS_FRACTION`. It shows how much of the gap "
              "comes from the capacitance convention; changing the RC engine is the M4 "
              "owner's decision."]

    lines += ["", "## Mesh convergence (PRD §14.7)", "",
              "Zone air temperature difference of each mesh against the finest mesh run "
              "for that case (same package inputs, only `element_size_m` changes).", "",
              "| Case | Element size m | Nodes | Max abs diff vs finest °C (worst zone) | Mean abs diff °C (worst zone) |",
              "|---|---|---|---|---|"]
    for case, levels in MESH_LEVELS.items():
        jobs = {}
        for size in levels:
            root = EVIDENCE_DIR / case if size == STANDARD_SIZE else \
                EVIDENCE_DIR / "mesh_check" / case / f"h{size:.2f}"
            j = _completed(root)
            if j:
                jobs[size] = j
        if not jobs:
            continue
        finest = min(jobs)
        idx["mesh_check"][case] = {}
        for size in sorted(jobs, reverse=True):
            sm = json.loads((jobs[size] / "solver_manifest.json").read_text(encoding="utf-8"))
            d = _diff(jobs[size], jobs[finest]) if size != finest else {}
            worst_max = max((v["max_abs_diff_c"] for v in d.values()), default=0.0)
            worst_mean = max((v["mean_abs_diff_c"] for v in d.values()), default=0.0)
            idx["mesh_check"][case][f"{size:.2f}"] = {
                "job": jobs[size].relative_to(EVIDENCE_DIR).as_posix(),
                "nodes": sm["nodes"], "vs_finest": d}
            lines.append(f"| {case} | {size:.2f}{' (finest)' if size == finest else ''} | "
                         f"{sm['nodes']} | {worst_max:.3f} | {worst_mean:.3f} |")

    case, sub = TIMESTEP_CHECK
    j_std = _completed(EVIDENCE_DIR / case)
    j_fine = _completed(EVIDENCE_DIR / "timestep_check" / case / f"substeps{sub}")
    if j_std and j_fine:
        d = _diff(j_std, j_fine)
        idx["timestep_check"][case] = {"dt_standard_s": 900, "dt_fine_s": 3600 / sub,
                                       "diff": d}
        worst = max(v["max_abs_diff_c"] for v in d.values())
        lines += ["", "## Timestep check", "",
                  f"{case}: 900 s vs {3600 / sub:.0f} s steps, worst zone max abs difference "
                  f"**{worst:.3f} °C**."]

    lines += ["", "## Modelling scope and known limits", "",
              "- Rectangular zones; partitions and inter-storey slabs are single interface stacks "
              "in a gap inserted at the shared plane, so zone sizes and surface areas equal the "
              "contract exactly. Junction strips/columns belonging to no surface are adiabatic "
              "(the RC model also ignores junction bridging).",
              "- Windows/doors: interior film + orthotropic core matching the contract U; "
              "window solar enters as heat flux on the zone's floor slab, as in the validated "
              "single-zone model.",
              "- Excluded on both sides: heating, infiltration, door-opening and stair airflow, "
              "opaque-surface solar, long-wave sky exchange. MAPDL here validates conduction "
              "through the envelope, partitions and slabs, not indoor airflow (no CFD claim).",
              "- ANSYS air is a high-conductivity solid per zone (near-isothermal node); the "
              "reported ANSYS zone temperature is its volume-weighted mean.",
              "- Exterior convection on ANSYS's opaque wall/roof faces uses a named, bounded, "
              "wind-speed-dependent film coefficient (McAdams 1954 simple combined: "
              "h = 5.7 + 3.8*V, 5-50 W/m2K, no windward/sheltered split since the weather "
              "source carries no wind direction). Openings and ground floors, and the whole "
              "RC side, keep the static contract h_outside (RC has no per-hour U input) - "
              "a disclosed, ANSYS-only refinement and an additional source of the gap below.",
              "- The RC comparison uses multiroom_rc's lumped node with the "
              "`EFFECTIVE_MASS_FRACTION` capacitance convention; differences therefore include "
              "that modelling choice, which is what this validation is meant to expose.",
              "- The legacy `benchmarks/ansys_reference` package is quarantined "
              "(`ansys-pipeline/quarantined/QUARANTINE.md`) and is not evidence."]
    write_json(EVIDENCE_DIR / "EVIDENCE_INDEX.json", idx)
    (EVIDENCE_DIR / "M8_VALIDATION_REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    # stdout on the Windows console is often cp1252, which cannot encode
    # U+2212 (minus) etc.; the file above already has the exact text.
    try:
        print("\n".join(lines))
    except UnicodeEncodeError:
        print("\n".join(lines).encode("ascii", "replace").decode("ascii"))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true", help="only regenerate the report")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--recompare", action="store_true",
                    help="re-derive RC comparison of the completed standard cases, no re-solve")
    a = ap.parse_args()
    if a.recompare:
        for case in CASES:
            j = _completed(EVIDENCE_DIR / case)
            if j:
                print(f"[evidence] recompare {case}: {recompare(j).metrics}")
    elif not a.report:
        run_all(force=a.force)
    report()
