/**
 * Builds components/viewer/viewerHtml.generated.ts — the self-contained HTML
 * page the 3D viewer WebView loads. It inlines a tree-shaken three.js
 * (viewer/three-entry.js, bundled by esbuild) and viewer/viewer.js, so the
 * viewer works offline and loads nothing from the network.
 *
 * Run after changing viewer/*: npm run build:viewer
 */
const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");

async function main() {
  const three = await esbuild.build({
    entryPoints: [path.join(root, "viewer", "three-entry.js")],
    bundle: true,
    minify: true,
    format: "iife",
    globalName: "THREE",
    write: false,
    legalComments: "none",
  });
  const threeJs = three.outputFiles[0].text;
  const viewerJs = fs.readFileSync(path.join(root, "viewer", "viewer.js"), "utf8");
  const threeVersion = require(path.join(root, "node_modules", "three", "package.json")).version;

  const html = [
    "<!doctype html><html><head><meta charset=\"utf-8\">",
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\">",
    "<style>html,body{margin:0;height:100%;overflow:hidden;background:transparent;touch-action:none}",
    "canvas{display:block;width:100%;height:100%}</style></head>",
    "<body><canvas id=\"c\"></canvas>",
    `<script>${threeJs}</script>`,
    `<script>${viewerJs}</script>`,
    "</body></html>",
  ].join("");

  const out = [
    "/* AUTO-GENERATED by scripts/build-viewer.js — do not edit. */",
    `/* three.js ${threeVersion} (tree-shaken, MIT licence) + viewer/viewer.js */`,
    `export const VIEWER_THREE_VERSION = ${JSON.stringify(threeVersion)};`,
    `export const VIEWER_HTML: string = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
  const target = path.join(root, "components", "viewer", "viewerHtml.generated.ts");
  fs.writeFileSync(target, out);
  console.log(`wrote ${path.relative(root, target)} (${(out.length / 1024).toFixed(0)} KB)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
